### ISSUE TITLE
为"无加密"加密算法确定标准命名

### ISSUE THREAD

**Issue by studentmain** [shadowsocks/shadowsocks-org#161]
希望在无加密可能得到广泛支持之前尽快确定其标准命名。

目前 ss 对无加密惯用`plain`，ssr 对无加密标准化为`none`。个人建议将无加密命名为`none`以减少支持多协议的软件的问题。

**Comment by studentmain** [comment]
@madeye @Mygod @zonyitoo

**Comment by zonyitoo** [comment]
`plain` was originally a debug feature. Why you need shadowsocks without shadow? :{

**Comment by studentmain** [comment]
Sure, we won't suggest use them now, but more and more implementation had it, and it's name cause some conflict... 

We need an instruction: 

1. Should other implementation implement them?
2. If they had this feature, should it be exposed to normal user?
3. And if they implemented it, which name should it use?

**Comment by TheWanderingCoel** [comment]
I may suggest use ``none`` instead of ``plain`` is this phenomenon. Since ``none`` is easy to understand and if a gui software implement ss/ssr protocol at the same time, it may increase their work to do.

**Comment by madeye** [comment]
Let's keep using `plain` for plain text. I don't think `none` is a valid name for encryption method.

**Comment by Qv2ray-dev** [comment]
I may suggest `none`, for it means `no` or `nothing`, one may not understand what a `plain` encryption but he could know what `no` encryption means.

**Comment by madeye** [comment]
First of all, `plain` or `none` is not part of shadowsocks protocol. So, actually this discussion doesn't make any sense.

For any client supports multiple protocols, you're free to use any name for your supported encryption methods.

The bottom line is make sure you follow all the official cipher names of shadowsocks. They can be found here: http://shadowsocks.org/en/spec/AEAD-Ciphers.html

**Comment by zonyitoo** [comment]
> First of all, plain or none is not part of shadowsocks protocol. So, actually this discussion doesn't make any sense.

I think @studentmain is trying to make `plain` or `none` part of shadowsocks' protocol standard.

**Comment by madeye** [comment]
I think any client can keep `plain` or `none` as a debug feature, but it should not be a protocol standard.

**Comment by zonyitoo** [comment]
I think it could be a implementation suggenstion. Suggests implementations those want to have a `plain` or `none` debugging feature should call it `plain` or `none`, or both.

**Comment by madeye** [comment]
BTW, I prefer `明文` to `无加密` for Chinese translations.

**Comment by Mygod** [comment]
To weigh in my opinion, I think `none` makes more sense under the context where no encryption is intentional, e.g. using it with some TLS plugin. `plain` implicitly implies that there should be a corresponding cipher text. If we keep it as a debugging feature, using either doesn't matter -- if we want this as an intentional feature, I prefer `none`.

**Comment by madeye** [comment]
Well, maybe make `none` as an implementation suggestion, not a new spec of shadowsocks protocol. At least it can reduce the confusion here.

**Comment by studentmain** [comment]
> 
> 
> I think it could be an implementation suggenstion. Suggests implementations those want to have a `plain` or `none` debugging feature should call it `plain` or `none`, or both.

Yes, that's what I mean.

**Comment by studentmain** [comment]
So, the answer is this, right?

All shadowsocks implemetation MUST has that 4 AEAD cipher, they MAY has other cipher, if an implemetation has a cipher which cipher text is same as plain text, that cipher SHOULD named as `none`.

**Comment by riobard** [comment]
> All shadowsocks implemetation MUST has that 4 AEAD cipher, they MAY has other cipher

Technically if you read [the spec](https://shadowsocks.org/en/spec/AEAD-Ciphers.html) carefully, a compliant Shadowsocks implementation only needs to implement AEAD_CHACHA20_POLY1305 (“must implement”). The three AEAD_AES_*_GCM variants are highly recommended (“should implement”) for implementations making use of hardware-accelerated AES instructions for efficiency gains (higher throughput and/or longer battery life).

The choice is because C20P1305 is a safe and efficient default for all devices, regardless of hardware AES support. AES-GCM modes are notoriously hard to implement efficiently and safely in software alone, so only recommended for hardware-accelerated AES implementations. I also regret putting AEAD_AES_192_GCM in the table as it is never used and has some security pitfalls.

Unfortunately many implementations are incapable of utilizing hardware AES instructions even on devices with hardware AES support. Earlier this year I did an informal survey of popular Shadowsocks client on iOS and found that thus far only Surge can do hardware accelerated AES-GCM.

Therefore for all intents and purposes, just use C20P1305.
