### ISSUE TITLE
Proposal for adding aes-ctr method in spec.

### ISSUE THREAD

**Issue by edsgerlin** [shadowsocks/shadowsocks-org#21]
AES in CFB mode is not supported by WebCrypto in major browsers, so to implement a Chrome OS version of Shadowsocks, developers have to do encryption in JavaScript, which is slow even with asm.js(about 40MiB/s+ vs 300MiB/s+ with modern x86 processor, could be 1GiB+ with AES-NI intrinsics). 
AES in CTR mode is supported by most WebCrypto implementations, and it is trivial to implement in most server side implementations of shadowsocks.
Some implementations(e.g shadowsocks-chromeapp) already have CTR mode support. I think it is best to add CTR mode to spec.

**Comment by Mygod** [comment]
LGTM. [Related information](https://www.chromium.org/blink/webcrypto).

**Comment by madeye** [comment]
LGTM. Added via https://github.com/shadowsocks/shadowsocks-libev/commit/9e407a943335c53aefd1285043d12ea247240376

**Comment by meowlab** [comment]
Thanks for your proposal.

Actually the bottleneck of chrome app is not only at the crypto performance, the design of JavaScript socket API and the V8 GC are also terrible for the heavy data traffic. That's the reason why I put the emphasis on the native client version. You can see further discussion here: https://github.com/shadowsocks/shadowsocks-chromeapp/issues/21, https://github.com/shadowsocks/shadowsocks-chromeapp/issues/15 and
https://github.com/shadowsocks/shadowsocks-chromeapp/issues/1.

But even there are many weak points in chrome app, I still think use WebCrypto API instead of JS library like forge is necessary, so, LGTM.

**Comment by edsgerlin** [comment]
@meowlab FYI https://bugs.chromium.org/p/chromium/issues/detail?id=585566  dskaram is working on a PPAPI for AES-NI. This might be useful for your NaCl version.

**Comment by meowlab** [comment]
@edsgerlin Woo, that's great. Thanks for letting me know that.

**Comment by wongsyrone** [comment]
Added in https://github.com/shadowsocks/shadowsocks-windows/commit/2fafc52defe6180e66f1e8d2a38d3668b99782cb

**Comment by librehat** [comment]
Added for Qt implementation https://github.com/shadowsocks/libQtShadowsocks/commit/2959fffe80780737b67be725636dd5e1ede8c59e

**Comment by wongsyrone** [comment]
@madeye I think it is time to add this to the website.
