### ISSUE TITLE
Documentation for master key generation

### ISSUE THREAD

**Issue by DarienRaymond** [shadowsocks/shadowsocks-org#98]
It seems that the master key generation algorithm is not documented anywhere on the [website](https://www.shadowsocks.org/). The algorithm to generate a master key from user-specified password for encryption/decryption use. It also worth noticing that this algorithm is used for both stream ciphers and AEAD ciphers.

One implementation of the algorithm is [here](https://github.com/shadowsocks/shadowsocks/blob/master/shadowsocks/cryptor.py#L54).

**Comment by madeye** [comment]
It's an old design issue that master key is generated using `EVP_BytesToKey()` function, which is described here: https://wiki.openssl.org/index.php/Manual:EVP_BytesToKey(3)

According to previous discussions, we keep using this approach in our implementations. But it's always better to use random keys instead of weak password.

So, if you want to keep compatibility with old implementations, just use this function to generate keys. If not, please feel free to use any other secure key generation approach or suggest users to input random keys instead.

**Comment by DarienRaymond** [comment]
I am afraid the "if not" part is not really practical. All Shadowsocks implementations use this algorithm and none of them offers alternative methods. Any new implementation will have to use the same logic, otherwise it can't connect with existing implementations.

What I am asking is to mention this translation from user's password to master key in the documents. This is helpful for other developers understand and implement Shandowsocks protocol.

**Comment by madeye** [comment]
Actually all the latest client/server accepts `--key` option. It's well discussed in https://github.com/shadowsocks/shadowsocks-org/issues/35.

**Comment by madeye** [comment]
But of course it's good to add this spec to our document and mention the potential issue of current key derivation.
